name: OIDC Login Test

on:
  workflow_dispatch:   # manual run button
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: "535791e2-810d-4282-9306-5c766dc8ede3"
  AZURE_TENANT_ID: "4a9d889e-4601-47a2-b372-45d4a2ea8d05"
  AZURE_SUBSCRIPTION_ID: "053a9f3d-903a-4386-aa02-6f75899c82d2"

jobs:
  login-test:
    runs-on: ubuntu-latest
    environment: prod   # MUST match Entra federated credential

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Show Azure Account
      run: |
        az account show
        az group list
